### ISSUE TITLE
Create post v1.15 version

### ISSUE THREAD

**Issue by bpatel85** [raff/tls-ext#1]
Let me start by saying that [this is](https://github.com/golang/go/issues/6379) very helpful discussion. I am implanting a service in Go (v1.16.x) and it needs to communicate to age old IOT devices using TLS-PSK. 

I am not an active Golang developer, but I see that the `crypto` package has gone through some code changes in `v1.15`.  Do you plan to release another version of this which is updated somewhat recent version of `crypto\tls` package?

**Comment by bpatel85** [comment]
Created https://github.com/raff/tls-ext/pull/2 to upgrade things with `crypto\tls` code from `v1.16.5 release branch`.

**Comment by raff** [comment]
Given that you are communicating with older device do you need any specific feature of 1.16 TLS ? Otherwise I would use this as is. 

This package is a complete duplicate of Go crypto/tls, so it doesn't need to be updated to match the Go version (unless something is broken and/or you need some specific feature).

(note that you need to use the tls13 branch with latest version of Go).

**Comment by bpatel85** [comment]
Thanks for your feedback
